# Contains hard coded variables for testing
from numpy import nan

test_scrap_results = dict(game_list=[
    {'@id': '4321', '@source': 'KOTLOL.com', 'path': './Metal Gear (USA).zip', 'name': 'Metal Gear',
     'desc': 'Near the end of the 20th century, a small fortified nation named Outer Heaven (founded by a mysterious war hero whose name and identity are shrouded in secrecy) is threatening the nations of the "West" with the development of a new prototype weapon named Metal Gear, a walking tank which is capable of launching nuclear warheads from anywhere on the globe. As FOX-HOUND\'s (an elite black ops unit) newest recruit, going by the codename of Solid Snake, your mission is to infiltrate Outer Heaven and rescue your missing comrade, Grey Fox.',
     'rating': '0.75', 'releasedate': '19880602T000000', 'developer': 'Konami', 'publisher': 'Konami',
     'genre': 'Action', 'players': '1', 'hash': 'F0E48ABE', 'image': './boxart/Metal Gear (USA).jpg',
     'video': './snaps/Metal Gear (USA).mp4', 'system': 'NES', 'folder': 'nes'},
    {'@id': nan, '@source': nan, 'path': './Rad Racer (USA).zip', 'name': 'Rad Racer',
     'desc': 'Rad Racer is an arcade style 3-D racing game. The object of the game is to race to the goal within the given time limit. Along each course are several checkpoints which will increase the amount of time you have to reach the final destination. There are eight different stages with increasingly difficult roads, changing weather conditions, and a variety of opponents who tend to get in the way. Included with the game is an optional pair of red-blue 3-D glasses which can be used to give the game an even more 3-D appearance.',
     'rating': '0.7', 'releasedate': '19871001T000000', 'developer': 'Square', 'publisher': 'Sega', 'genre': 'Racing',
     'players': nan, 'hash': nan, 'image': './boxart/Rad Racer (USA).jpg', 'video': './snaps/Rad Racer (USA).mp4',
     'system': 'NES', 'folder': 'nes'},
    {'@id': nan, '@source': nan, 'path': './Snake Rattle n Roll (USA).zip', 'name': "Snake, Rattle 'n Roll",
     'desc': "Snake, Rattle 'n Roll is an isometric 3D platformer. The object of each level is to eat as many Nibbley Pibblies (round creatures of various colours) as possible to make your snake heavy. Once it's heavy enough, you must stand on the scales in the level, and if you're heavy enough, the door will open and you can make your way to the exit.",
     'rating': '0.8', 'releasedate': '19900701T000000', 'developer': 'Rare,\xa0Ltd.', 'publisher': 'Nintendo',
     'genre': 'Action', 'players': '1-2', 'hash': nan, 'image': './boxart/Snake Rattle n Roll (USA).jpg',
     'video': './snaps/Snake Rattle n Roll (USA).mp4', 'system': 'NES', 'folder': 'nes'},
    {'@id': nan, '@source': nan, 'path': "./Super Mario World 2 - Yoshi's Island (USA, Asia) (Rev 1).zip",
     'name': "Super Mario World 2: Yoshi's Island", 'desc': 'For Testing Purposes.', 'rating': '0.95',
     'releasedate': '19951004T000000', 'developer': 'Nintendo', 'publisher': 'Nintendo', 'genre': 'Platform',
     'players': nan, 'hash': nan, 'image': "./boxart/Super Mario World 2 - Yoshi's Island (USA, Asia) (Rev 1).jpg",
     'video': "./snaps/Super Mario World 2 - Yoshi's Island (USA, Asia) (Rev 1).mp4", 'system': 'Super Nintendo',
     'folder': 'snes'},
    {'@id': '1234', '@source': 'KOTLOL.com', 'path': './Uncharted Waters (USA).zip', 'name': 'Uncharted Waters',
     'desc': 'For Testing Purposes.', 'rating': '0.55', 'releasedate': '19930102T000000', 'developer': 'Koei',
     'publisher': 'Koei', 'genre': 'Role playing games', 'players': '1', 'hash': '95724A2F',
     'image': './boxart/Uncharted Waters (USA).jpg', 'video': './snaps/Uncharted Waters (USA).mp4',
     'system': 'Super Nintendo', 'folder': 'snes'}], skip_list=['dummy'])